<?php

namespace Doctrine\Bundle\DoctrineBundle\Repository;

/**
 * entity1Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class entity1Repository extends \Doctrine\ORM\EntityRepository
{
}
