<?php

namespace Mozenta\MozentaBundle\Repository;

/**
 * MozantaEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MozantaEntityRepository extends \Doctrine\ORM\EntityRepository
{
}
